# Module: NumPy Assignments
## Lesson: NumPy












### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
import numpy as np

arr1 = np.random.randint(1,21,size=(5,5))
arr1
arr1[:, 2] = 1#need all the rows :, and that 2nd col need to be replaced 1
arr1

arr2 = np.arange(1,17).reshape(4,4)
arr2
np.fill_diagonal(arr2,0)
arr2

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [ ]:
import numpy as np
arr1 = np.arange(1,37).reshape(6,6)
arr1[2:5,1:4]
arr2 = np.random.randint(1,21,size = (5,5))#need range all the time

#extract and add
border_elements = np.concatenate((arr2[0,:],arr2[-1,:],arr2[1:-1,0],arr2[1:-1,-1]))
border_elements


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
arr1 = np.random.randint(1,13,size=(3,4))
arr2 = np.random.randint(1,13,size=(3,4))
arr1+arr2
arr1-arr2
arr1*arr2
arr1/arr2

arr3 = np.arange(1,17).reshape(4,4)
arr3.sum(axis=0)#col
arr3.sum(axis=1)#row


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
arr1 = np.random.randint(1,26,size=(5,5))
arr1.mean()
median = np.median(arr1)
print(median)
# arr1.std()
print(arr1.var())

arr2 = np.arange(1,10).reshape(3,3)
mean = np.mean(arr2)
std  = np.std(arr2)
normalised_data = (arr2 - mean)/std
print(normalised_data)


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
arr1 = np.random.randint(1,13,size=(3,3))
row_arr1 = np.random.randint(1,13,size=(3,))
res = arr1 + row_arr1
res
# arr1 = np.random.randint(1,13,size=(4,4))
# col_arr1 = np.random.randint(1,13,size=(4,))
res = arr1 - col_arr1[:, np.newaxis]#for col operation
res


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)#causes singular matrix as determinant is zero so use random
matrix = np.random.randint(1, 11, size=(3, 3)) #solves that error
# arr1
#Under linalg class

np.linalg.det(matrix)
np.linalg.inv(matrix)
print((np.linalg.eig(matrix))[0])

arr1 = np.random.randint(1, 7, size=(2, 3))
arr2 = np.random.randint(1, 7, size=(3, 2))

#matmul very imp operation
matrix_mul = np.linalg.matmul(arr1,arr2)
#OR np.dot for simpler but for complex Ndim array matmul
print(matrix_mul)

[13.71323052  2.3538238  -3.06705432]
[[22 21]
 [28 27]]



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [96]:
arr1 = np.arange(1,10).reshape(3,3)
arr1.reshape(1,9)
arr1.reshape(9,1)

arr1 = np.random.randint(1,20,size=(5,5))
arr1.flatten()
arr1.reshape(5,5)


array([[17, 13, 15, 12, 11],
       [ 3, 15, 19, 18,  5],
       [ 1, 16,  2,  7, 19],
       [12, 11,  6, 16, 12],
       [17, 13, 10, 10, 18]], dtype=int32)


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.