In [ ]:
import numpy as np

##create arrays using np

arr1 = np.array([1,2,3,4,5])#not rows or cols just a single dimension array
arr1.reshape(1,5) # 1 row and 5 cols 2d array
# can use nested lists as well to create a 2d or 3d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6],[0,0,0,0,0]])# 2 opening and closing brackets hence 2 dimensional array
print("arr2 shape:", arr2.shape)
print("Number of dimensions (ndim):", arr2.ndim)
print("So, arr2 has", arr2.shape[0], "rows and", arr2.shape[1], "columns.")

# In numpy, "2D" means two axes (rows and columns), not "2 rows".
# "3D" means three axes (e.g., layers, rows, columns), not "3 rows".

arr2 shape: (3, 5)
Number of dimensions (ndim): 2
So, arr2 has 3 rows and 5 columns.


In [ ]:
# np.arange(0,10,2)
np.arange(0,10,2).reshape(5,1) # convert to 1d, 2d ,3d 

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr2.ndim#dimensions 
arr2.shape#shape as in number of elements.
arr2.dtype#data type int32 like that
arr2.itemsize #(bytes)

(3, 5)

In [29]:
#few useful functions with matrices all works element wise
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

print("Addition:\n", np.add(arr1, arr2))
print("Subtraction:\n", np.subtract(arr1, arr2))
print("Multiplication:\n", np.multiply(arr1, arr2))
print("Division:\n", np.divide(arr1, arr2))

print("Sine:\n", np.sin(arr1))
print("Exponential:\n", np.exp(arr1))
print("Logarithm:\n", np.log(arr1))




Addition:
 [ 2  4  6  8 10]
Subtraction:
 [0 0 0 0 0]
Multiplication:
 [ 1  4  9 16 25]
Division:
 [1. 1. 1. 1. 1.]
Sine:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exponential:
 [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [37]:
arr = np.arange(1,13).reshape(3,4)

In [58]:
#slicing:
print(arr[0:2,2:])# 0 - n-1 works [r,c]
print(arr[0:2][2:]) # no works
print(arr[1:,1:3]) 

[[3 4]
 [7 8]]
[]
[[ 6  7]
 [10 11]]


In [59]:
arr[0][0] = 100 #modifying values
arr[2:] = 100

In [60]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [100 100 100 100]]


In [62]:
#statistic concept:
# normalisation - to have mean as 0 and standard deviation as 1
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std  = np.std(data)
normalised_data = (data - mean)/std
print(mean)
print("Normalised data: \n", normalised_data)

#median variance
# np.median
# np.var

3.0
Normalised data: 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [71]:
#logical operations

data>5
data>1
data[(data>1) & (data <3)]


array([2])